version: '3.5'

services:
  joomla:
    image: joomla:3
    restart: always
    links:
      - joomladb:mysql
    ports:
      - "${WEB_PORT80}:80"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
